<?php
/**
 *Implementation of hook_menu for JsonTeach4America
*/
function JsonTeachAmerica_menu(){
   $items = array();
   $items['post_import']= array(
    'title' => t('Import post'),
    'description' => t('Import post in json format to drupal and create a post node for each items'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('import_json_form'),
    'access arguments' => array('View Import Form'), 


    );
  
 return $items;


}
/**
 * Implement hook permission to view and submit the form
 */

 function JsonTeachAmerica_permission(){
   return array('Import Json data' => array(
      'title'=>t('View Import Form'),
      'description' =>t('view and submit the form'),
),
  );

}

/**
 *define the call back function to retrieve the form
 */
//function display_form(){
  //return drupal_get_form('import_json_form');

//}
function import_json_form($form, $form_state){

  $form['web_url']=array(
    '#title' => t('Source url'),
     '#type' => 'textfield',
      '#description'=> t('Enter the source url from where we import'),
      '#required' => TRUE,
     );
   $form['submit']= array(
      '#type' => 'submit',
      '#value' => t('Import'),
    );
    return $form;

   

}
/**
* Validation handler for the form to see if it's valid url
/*
function import_json_form_validate($form, &$form_state){
  $url = $form_state['values']['web_url'];
  

// Validate url
  if (!valid_url($url){
   $message =t('the url %web_url is not a valid url.Please re-enter your address.', array('%web_url' -> $url));
   form_set_error('web_url', $message);
   }
}

/**
 * form submission handler
*/
function import_json_form_submit($form, &$form_state){
  // get the url 
  $url = $form_state['values']['web_url'];
  
  // make request to get the data
  $request = drupal_http_request($url);
 //  dpm($request->data);
  
    if (($request->code!=200)){ 
       drupal_set_message("URL request ({$url}) returned unexpected status code".$request->code.","." error:".$request->error);
        return FALSE;
    } 
    // else uses drupal_json_decode to turn into array
  
    $json_response = json_decode($request->data);
  
    dpm($json_response);
   //dpm($request->code)

  //  var_dump($json_response);:

 
   if (isset($json_response)){
     foreach ($json_response as $response_data ) {

           $node = new StdClass();
         //creating a bare node

           $node->type = 'post';
         //giving it type
          $node->language = LANGUAGE_NONE;
          $node->status = 1;
         //give it a published staus

           $node->title = $json_response->series;
          //gives title

          $node->body = $json_response->total;
          //gives body

           node_save($node);

}
//dpm($url);
}
}
